// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBufSlXgNAhYA3jNG_cjU8dRMMj-BsOPWQ',
    appId: '1:158957688001:web:1fe7e82d986ca7b7eeb040',
    messagingSenderId: '158957688001',
    projectId: 'chatterhook-a3810',
    authDomain: 'chatterhook-a3810.firebaseapp.com',
    storageBucket: 'chatterhook-a3810.appspot.com',
    measurementId: 'G-ZFHYPCRKVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtbHnucOswCtIreKX50PNe_pLucA-iHmI',
    appId: '1:158957688001:android:4ed98cc4763827f5eeb040',
    messagingSenderId: '158957688001',
    projectId: 'chatterhook-a3810',
    storageBucket: 'chatterhook-a3810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXq2ATQ9-jw6lvQtBAIpN0xoNT9fBJkCE',
    appId: '1:158957688001:ios:551a2b01b2bf4c05eeb040',
    messagingSenderId: '158957688001',
    projectId: 'chatterhook-a3810',
    storageBucket: 'chatterhook-a3810.appspot.com',
    iosBundleId: 'com.example.chatternook',
  );
}
